---
- hosts: localhost
  vars_prompt: 

    - name: username
      prompt: "Enter user name: "
      private: no
   
    - name: password
      prompt: "Enter password"
      private: yes
      encrypt: "sha512_crypt" 
      confirm: yes
      salt_size: 7

  tasks: 
    - debug: 
         #msg: 'Logging in as {{ username }}'
         msg: 'Passowrd is {{ password }}'
      tags:
        - user
